prop: {
    propName: "A";
    propValue: "aaa";
};
prop: {
    propName: "C";
    propValue: "ccc";
};
prop: {
    propName: "D";
    propValue: "ddd";
};
prop: {
    propName: "XX";
    propValue: "v1";
};
prop: {
    propName: "XX";
    propValue: "v2";
};
prop: {
    propName: "XX";
    propValue: "v3";
};
prop: {
    propName: "XX";
    propValue: "v4";
};
prop: {
    propName: "XX";
    propValue: "v5";
};
prop: {
    propName: "B";
    propValue: "bbb";
};
